### ISSUE TITLE
Wire does not work in Franz: Dieser Browser wird nicht unterstützt.

### ISSUE THREAD

**Issue by hannesdorn** [wireapp/wire-webapp#1209]
Wire for Web Version: Version 2017-05-03
Browser Version: Franz 4.0.4
Installed Browser Addons: None
OS: Windows 10 1704

What steps will reproduce the problem?
1. Install http://meetfranz.com/
2. Add Wire
3. See error message: Dieser Browser wird nicht unterstützt.

What is the expected result?
A working wire

What happens instead?
Dieser Browser wird nicht unterstützt.

Please provide any additional information below. Attach a screenshot if
possible.

![capture_05102017_205313](https://cloud.githubusercontent.com/assets/10920147/25916023/998f4c12-35c3-11e7-8db9-e6c9590fcbd1.png)

With kind regards
Hannes Dorn

**Comment by gregor** [comment]
@hannesdorn Franz was deliberately blocked by https://github.com/wireapp/wire-webapp/releases/tag/2017-04-20-15-54 due to a very problematic security setting that caused an incompatibility with the webapp due to a bug in Chrome. We pinged the Franz team on multiple channels but have not gotten a reply. There are no plans to reenable support for Franz while this is not addressed by the Franz team. Thereby closing this issue.

**Comment by bittner** [comment]
Is or will it be possible to add Wire to Franz again? Has the mentioned "deliberate blocking" been removed in the meantime?

**Comment by hannesdorn** [comment]
btw, in the meantime I switched to Rambox, which supports Wire.
