### ISSUE TITLE
Feature request: Option to turn off emojis

### ISSUE THREAD

**Issue by Fogelholk** [wireapp/wire-webapp#1263]
Not everyone likes emojis, I would like to request a button in the preferences to turn off/on emojis.

**Comment by max-baz** [comment]
Out of curiosity, what exact behavior bothers you today that you would like to be able to turn off in preferences?

1. When you type `:smile`, you don't want to see a popup with the list of suggested emojis.
2. When _you_ type `:)` in the message, you don't want it to be automatically converted to 🙂.
3. When _someone_ sends you 🙂, you want it to be automatically converted to `:)`.
4. Something else? 🙂

**Comment by Fogelholk** [comment]
Sorry for not clarifying, my requests are your option 2 and 3, whereas `:)` does not get converted to 🙂 on "my end" of the conversation.

The other side might want emojis and have the option turned on to show the yellow little fellas :)

**Comment by max-baz** [comment]
Option 2 is pretty easy to accomplish (given that Wire team approves the checkbox in preferences). Basically it's just a matter of adding `if (dontWantInlineEmojiReplacement) { return false; }` in the beginning of two functions, [_try_replace_inline_emoji](https://github.com/wireapp/wire-webapp/blob/c646ca544d2c709e27857c7ff46ef9fa59d4669c/app/script/view_model/ConversationInputEmojiViewModel.js#L231) and [_replace_all_inline_emoji](https://github.com/wireapp/wire-webapp/blob/c646ca544d2c709e27857c7ff46ef9fa59d4669c/app/script/view_model/ConversationInputEmojiViewModel.js#L250). 

Given that I already heard this request several times, I think it will be implemented 🙂

Option 3 is cool, but it is a completely different beast, it is a much more complicated task that requires parsing the received text and doing some pre-processing text replacements before the message is displayed to you. If this ever gets implemented, this will likely come much later. Just so that you know 🙂

**Comment by phoenixeliot** [comment]
I would like to be able to send the string `<3` without it being converted into the emoji heart character on my screen or the recipient's screen. I think this is option #2.

**Comment by balping** [comment]
@phoenixeliot wrote on May 23, 2017

> It appears that Wire has added one of my least-favorite antifeatures from Facebook Messenger, by making it impossible to type certain ascii sequences, instead forcing them into emojis that simply do not have the same emotional feeling for me (<3 especially).
> 
> I would love for there to at least be an option to turn this behavior off. I was pleasantly surprised when I originally started using Wire and it didn't do this behavior, and I'm disappointed that it's been forced upon me in my new favorite messenger.

I agree with you 100% and I'm pleased to see that hopefully there will be an option to turn this off. I'm really looking forward to it.

**Comment by gregor** [comment]
A preference to disable the auto replacement was added based on a contribution by @balping. It will be part of the release early next week.

**Comment by bennycode** [comment]
**Good news!**

You can now turn on/off emojis in Wire:

![unbenannt](https://user-images.githubusercontent.com/469989/27547075-12e83128-5a95-11e7-8248-7da5f0ace0b2.PNG)
