### ISSUE TITLE
UI inconsistency in user profile popover

### ISSUE THREAD

**Issue by regexident** [wireapp/wire-webapp#14]
The OS X client shows `+ ADD PEOPLE` in the lower left corner, while the web client, as well as the iOS client show `🙎+ CREATE GROUP` in the lower left corner.

---

Likewise both, OS X and Web client show `⊘` in the lower right corner, while iOS shows `⋯`.

**Comment by bennycode** [comment]
Hi @regexident, thanks for your report.

Can you please add a screenshot of the defect? Because on my machine it shows "Add people" for both (wrapper version/OS X client/Windows client + webapp version) platforms.

**Screenshot:**

![unbenannt](https://cloud.githubusercontent.com/assets/469989/17133117/174940ae-5325-11e6-85ba-3d5e18948f50.PNG)

**Comment by regexident** [comment]
The web client was a local clone of [wireapp/wire-webapp](https://github.com/wireapp/wire-webapp/).

![create-group](https://cloud.githubusercontent.com/assets/138017/17148183/582ee088-5366-11e6-9b74-72285603797d.png)

---

Those are some hilarious chat groups, btw. 😂

**Comment by gregor** [comment]
`🙎+ CREATE GROUP`  is the new copy which will be visible on the OS X client as soon as we next release our web component.
