### ISSUE TITLE
Site tells me I have another tab open when I don't. How to fix?

### ISSUE THREAD

**Issue by dysinger** [wireapp/wire-webapp#1457]
## Wire for Web Version
<meta property="wire:version" version="2017-06-28-15-13-prod">

## Browser Version
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/58.0.3029.110 Chrome/58.0.3029.110 Safari/537.36

## Installed Browser Addons
HTTPS Everywhere, The Great Suspender, 

## Operating System
Linux (Ubuntu latest)

## What steps will reproduce the problem?
1. Open two tabs of Wire
2. See error message
3. Still see the error message with only 1 tab

## What is the expected result?
No error

## What happens instead?
Error

![image](https://user-images.githubusercontent.com/447/27664562-111b0f44-5c1d-11e7-90c3-106854d71f0e.png)

**Comment by max-baz** [comment]
@dysinger the fix is landing to production as we speak, but you might have to use this workaround one more time: https://github.com/wireapp/wire-webapp/issues/1440#issuecomment-310829158

@gregor, @bennyn I have a general suggestion for the team, consider closing the issues not when the fix is merged in `dev`, but when the it reaches `prod`. I see you use labels, so maybe create a label `fixed in the next release` for such issues. It will help searching the issues and reduce duplicates, especially because default filter includes "search only open issues", and also help understanding if the fix actually reached the production already or not.

**Comment by gregor** [comment]
@maximbaz Thanks for the suggestion. Closing the issues is a feature of github. If you mention the issue number in your PR it will be closed as soon as you merge the fix. Will try to be more proactive and reopen to close manually again later.

**Comment by dysinger** [comment]
I did some basic searches on open tickets (the default) before creating this one. I didn't think to search closed tickets.

**Comment by max-baz** [comment]
@gregor just don't use the [special keywords](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues) in the title or body of PR or commits 🙂 

The lines like `Fixes #1440` is what makes github [automatically close the issue](https://github.com/blog/1506-closing-issues-via-pull-requests).

**Comment by bennycode** [comment]
@dysinger Your reported issue got addressed and is fixed now on [app.wire.com](https://app.wire.com/). 🙂 

Just let us know if you see further issues. 

Best from Berlin!

Benny

**Comment by dysinger** [comment]
I got it again this morning :|

![image](https://user-images.githubusercontent.com/447/28754631-af62eab6-74fd-11e7-8d29-01456fb62921.png)

**Comment by gregor** [comment]
@dysinger The detection is now based on a cookie timed for 5 minutes. If the browser crashes and we thereby fail to clear it. you can either manually delete it or wait 5 minutes - then you should be able to log in again.
