### ISSUE TITLE
Emoji is used as display name

### ISSUE THREAD

**Issue by cityroler** [wireapp/wire-webapp#1459]
## Wire for Web Version

2017.06.28.1513
## Operating System:
macOS

## What steps will reproduce the problem?
1. Change display name to something with ™-symbol in it

## What is the expected result?
It should be displayed the ™-symbol.

## What happens instead?
Instead of the ™-symbol the emoji is used and so the name is white and the emoji black

<img width="115" alt="screen shot 2017-06-29 at 15 06 09" src="https://user-images.githubusercontent.com/13933169/27688901-87e79894-5cdc-11e7-813f-255893fba1a9.png">

**Comment by max-baz** [comment]
I'll add some details, to help triage this report.

Emoji standard of Unicode 5.0 defines the [list of characters](http://unicode.org/Public/emoji/5.0/emoji-data.txt) to treat as emoji. This is the beginning of the list:

```
0023          ; Emoji                #  1.1  [1] (#️)       number sign
002A          ; Emoji                #  1.1  [1] (*️)       asterisk
0030..0039    ; Emoji                #  1.1 [10] (0️..9️)    digit zero..digit nine
00A9          ; Emoji                #  1.1  [1] (©️)       copyright
00AE          ; Emoji                #  1.1  [1] (®️)       registered
203C          ; Emoji                #  1.1  [1] (‼️)       double exclamation mark
2049          ; Emoji                #  3.0  [1] (⁉️)       exclamation question mark
2122          ; Emoji                #  1.1  [1] (™️)       trade mark
2139          ; Emoji                #  3.0  [1] (ℹ️)       information
2194..2199    ; Emoji                #  1.1  [6] (↔️..↙️)    left-right arrow..down-left arrow
21A9..21AA    ; Emoji                #  1.1  [2] (↩️..↪️)    right arrow curving left..left arrow curving right
231A..231B    ; Emoji                #  1.1  [2] (⌚..⌛)    watch..hourglass
```

I [excluded](https://github.com/wireapp/wire-webapp/blob/93a9d6f86d22becc19bf04124e9a71e8b0111dc1/app/style/common/variables.less#L34-L37) the first three lines (`0..9`, `#` and `*`) because they are certainly better off being rendered with regular font, and not as an emoji.

I'm not that confident that regular font will render `©️`, `®️` and the rest nicer than emoji font, that's why I left them to be rendered as emoji according to the standard. For example `⁉️` is rendered very beautifully as emoji on my laptop.

Based on that, decide whether you want to exclude more characters from the list that is defined by Unicode standard or not. If you do exclude some characters, the code needs to be changed [here](https://github.com/wireapp/wire-webapp/blob/93a9d6f86d22becc19bf04124e9a71e8b0111dc1/app/style/common/variables.less#L34-L41) and [here](https://github.com/wireapp/wire-webapp/blob/293bd72752a72bd4aa5694dc400601da6cfe84c5/app/script/util/Emoji.js#L26-L27).

------------

I also have contacts that use emoji in their name, and other dark emojis don't look particularly readable. For comparison, the light emojis look OK. Maybe this is a design issue in general, that many dark emojis don't look nice, and not the issue of choosing font to render `™️`.

![image](https://user-images.githubusercontent.com/1177900/27706759-07e9eb88-5d13-11e7-8e3f-a63283fbbfc0.png)

**Comment by max-baz** [comment]
So I've just found out that there is an official way of telling whether a certain glyph should be rendered as text or as emoji. What I did by removing glyphs from the list is merely a hack.

The true way: https://en.wikipedia.org/wiki/Emoji#Emoji_versus_text_presentation

In short, when you take a glyph like `3` (`U+0033`) or `™` (`U+2122`), this glyph alone doesn't tell how to render itself, an app can decide to render it however it pleases.

However, if you add an invisible character to it, according to the standard you are telling the app how to render it, like a text `3︎` (`U+0033, U+FE0E`) and text `™︎` (`U+2122, U+FE0E`) or like an emoji `3️` (`U+0033, U+FE0F`) and emoji `™️` (`U+2122, U+FE0F`).

Fascinating!

Unfortunately Wire doesn't respect this standard at the moment... 
(My Chrome doesn't seem to respect that too).

So short-term we can remove those `©️`, `®️` and `™︎` from the list and always render it as text.

The most correct way to solve this bug is:

1. Stop excluding chars defined by the standard.
2. Respect markers `U+FE0E` and `U+FE0F` to choose how to render a glyph, as a text or as a emoji.

This would allow some users to use numbers as emoji :one: and numbers as text `1`, same for all other characters like `©️`, `®️` and `™︎`.

--------------

@cityroler you should copy this character from here and put it in your name (it has invisible marker in it): `™︎`
When the bug is fixed, this will be rendered as text.

And don't get me wrong, I totally realize how ridiculous this sounds to ask users to copy a specific character which has invisible markers in it 😄

**Comment by max-baz** [comment]
More findings: looks like we can't implement the "most correct" solution because browsers don't actually respect these markers. For example, here's [a bug for Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=491556) tracking this issue.

So, made a PR https://github.com/wireapp/wire-webapp/pull/1489, it will make `™︎` always be rendered as text, and subscribed to the Chromium bug to hear when it is fixed 🙂

**Comment by gregor** [comment]
@maximbaz changes were part of today's deployment. The issue should be addressed and TM displayed as a regular font character instead of the emoji version again.
