### ISSUE TITLE
Wire web app doesn't work for me anymore, always displays " Wire is already open in another tab." message even if there is no other wire tab open

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-webapp#1474]
The wire web app doesn't work for me anymore: when I open it, it always displays  the "Wire is already open in another tab." message even if there is no other wire tab open.

## Wire for Web Version
`2017-06-28-15-13-prod`

## Browser Version
`Mozilla/5.0 (X11; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0`

## Installed Browser Addons
- ADB Helper
- HTTPS Everywhere
- uBlock Origin (disabled in the wire tab while testing this issue)
- User Agent Switcher (enabled but no non-default user agent active while testing this issue)
- Valence

## Operating System

GNU/Linux Ubuntu 17.04

## What steps will reproduce the problem?
1. Open https://app.wire.com

## What is the expected result?
It opens when no wire tab is open with no errors

## What happens instead?
I always get the error "Wire is already open in another tab." even when it isn't opened in another tab:

![wire_tab_error](https://user-images.githubusercontent.com/1573352/27827785-4c46360c-60b9-11e7-9f55-7aef2cc75307.png)

**Comment by gregor** [comment]
When did you start seeing this message? You probably used a broken version of the web app last week that set a cookie which is not getting properly removed. We have since build a fix and deployed it to production - but if you ran into the issue you still have follow the workaround detailed in https://github.com/wireapp/wire-webapp/issues/1440#issuecomment-310829158 once. Does this solve your problem?

**Comment by ghost** [comment]
Ah sorry about that, I missed the duplicates. Yes, removing the cookie solves it
