### ISSUE TITLE
No persistency between sessions if cookies and web storage are cleared

### ISSUE THREAD

**Issue by WalterS** [wireapp/wire-webapp#1816]
Browser: Firefox on Linux
For security and privacy reasons, all cookies and web storage are cleared when I close Firefox.
This prompts Wire to detect a new device and I lose all chat history and have to delete the "old" device from the list of devices.
There should be a method for detecting a device ID/fingerprint which doesn't rely on local storage.

**Comment by gregor** [comment]
The cryptographic identity of a client is created and stored in the IndexedDB. There is no way to recreate the same identity again, which is why Wire is secure. Our proteus protocol also relies on the state of a cryptographic session between two devices to be stored locally. Otherwise we could not offer to decrypt messages that you received while you were offline. What you are essentially asking for is Wire without encryption or without relying it to be end-to-end. You can read all about how Wire works in the whitepapers found at https://wire.com/privacy/
