### ISSUE TITLE
Add support for reply to comments

### ISSUE THREAD

**Issue by marfous** [wireapp/wire-webapp#182]
Common messanges are having reply-to possibility so one can connect (at least in the UI) one message with other one. It would be great to have it in the browser as well as in mobile apps - i.e. using long click on the message I want to reply, click reply and write test into common text box.

Thanks in advance.

**Comment by helenakos** [comment]
Hey @marfous, thanks for the feedback! Sounds like a good idea. We will consider it depending on the user demand.

**Comment by mohammadrafigh** [comment]
I want to go for this feature. but I have some questions:

anyone else is working on it? and is there a restriction in the backend apis to implement this (since it's close source yet I ask this)?

the first thing comes into my mind is just copy the replying message and format it using markdown's Blockquote syntax. but I assume I need to include the message id inside it too, so when user clicks on the replied message the message history scrolls to that message.

any thoughts?

by the way I can implement it on Android app too...

**Comment by EgbertW** [comment]
You would need the message ID or something to avoid sending duplicate content and to have the replied to message updated when the original message is edited, as a proper implementation should, IMO.

**Comment by helenakos** [comment]
Thanks for your request, we don't have it planned at the moment so closing this issue. 

On a side note, you can open an issue for general comments (not related to any client / specific repository) here: https://github.com/wireapp/wire
