### ISSUE TITLE
Wire is Not accessable through Tor Browser

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-webapp#1882]
## Wire for web version

not applicable (because i cant access it)

## Browser version

Tor Browser Bundle 7.5a7 (based on Mozilla Firefox 52.4.1) (64-bit)

## Installed browser addons

NoScript , Https Everywhere 

## Operating system

Debian Linux

## What steps will reproduce the problem?

open https://app.wire.com inside any TBB. 

## What is the expected result?

to see Wire is working though TBB, because this will give secure/anonymous/privacy protection connection. (comparing it to the clearnet connection)

## What is the actual result?

it says this message:-

`
Wire needs access to local storage to display your messages. Local storage is not available in private mode.`

**Comment by gregor** [comment]
We need access to the indexeddb. There is no way to keep any message history and persist the required encryption sessions without it.

**Comment by ghost** [comment]
so in other word there will be no working around for this feature due to design restriction ?

**Comment by fonixer** [comment]
@oonimooni You can always put your traffic through Tor and use an app version of Wire.
Wouldn't it work?

**Comment by ffflorian** [comment]
@oonimooni:
You can manually enable indexedDB in the Tor browser config. To do that, open `about:config` in your browser, search for `dom.indexedDB.enabled` and set the value to `true`. Reload [app.wire.com](https://app.wire.com) and it should work.

:warning: But please be aware of the fact that every other website you browse can then also save data in your indexedDB and this change will lower the security of the Tor browser. :warning:

**Comment by ghsrcgh** [comment]
On TOR Browser under windows there is no any such error messages.

Please make Browser WIRE working with the TOR Browser

When you are trying to open https://app.wire.com in TOR Browser (checked with 7.0.10 and before on Windows) it is starting to load, then you see a progress bar that is moving, but never ends. This is never stops. So, WIRE-Browser does not work in TOR Browser at all.

Is it the same issue with IndexedDB? Is any workarounds in WIRE, not in TOR (do not make TOR more insecure)?

**Comment by mythsunwind** [comment]
If you want to run Wire over Tor, please use Tor through its socks functionality described on https://www.torproject.org/docs/tor-manual.html.en and use the desktop client to route all traffic through the Tor socks proxy.

We recently added the instructions on how to connect through a proxy server on Wire desktop:
https://support.wire.com/hc/en-us/articles/115005697189-How-I-can-connect-through-a-proxy-server-on-desktop-

Since it is a bad idea to generally allow websites to write to IndexedDB in Tor Browser and Firefox has still an open issue regarding IndexedDB in private browsing mode (https://bugzilla.mozilla.org/show_bug.cgi?id=781982) I will close this ticket.
