### ISSUE TITLE
Please remove "browser support" detection using UserAgent: it fails on UA randomization

### ISSUE THREAD

**Issue by ghsrcgh** [wireapp/wire-webapp#1919]
I'm using the modern (latest) Chrome with special extension for UserAgent randomization. So, I cannot use app.wire.com, because of that message: https://wire.com/en/unsupported/
```
This browser is not supported.
Download the latest version of Google Chrome, Mozilla Firefox, Opera or MS Edge. Wire for macOS and Microsoft Windows are available from get.wire.com.
```
Ofcourse, it is incorrect, just it uses UserAgent for detecting browser version. It is a bad idea.

Please remove this check. (If you want special checks, you may do this with JavaScript, checking a work of some functions).

**Comment by gregor** [comment]
Thank you for your suggestion. We will not remove the browser check at this time. We whitelist a certain set of browsers on purpose to avoid a lot of noise to our support channels from users with outdated or otherwise unsupported configurations. It is in the nature of our app to rely on a number of modern browser APIs that are not fully stable and still change a lot between browser releases - while also showing implementation differences across vendors. We cannot test all possible combinations and thus try to keep the test matrix and the list of supported browsers lean in order to move faster with a small team.
