### ISSUE TITLE
"Edited on Invalid date" when editing message

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-webapp#205]
When I edit a message on the atom dekstop app, a pen is displayed after my name.
On a tool tip, it says: "Edited on Invalid date"

Something went wrong ?

**Comment by lipis** [comment]
Verified.. I have the same :) Thanks @IpsmLorem

**Comment by gregor** [comment]
@IpsmLorem Thank you very much for the report. I introduced this issue with the last release we deployed   last Thursday and uncovered only after the release. The bug has already been fixed in the codebase (https://github.com/wireapp/wire-webapp/pull/197) and the fix will be part of the next release.

**Comment by IpsmLorem** [comment]
Thank you.
