### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by dns2utf8** [wireapp/wire-webapp#2149]
## Browser version

chromium 63.0.3239.108-2

## Installed browser addons

AdBlock & Privacy Badger

## Operating system

Arch Linux

## What steps will reproduce the problem?

1. Login
2. See loading bar
3. Start over

## What is the expected result?

Logging in

## What is the actual result?

![image](https://user-images.githubusercontent.com/739070/34427433-6c6e1c78-ec42-11e7-83a3-ae14ee4d6611.png)

**Comment by mythsunwind** [comment]
It looks like one of your browser addons (AdBlock or Privacy Badger) is blocking a bit too much. I tried to reproduce the issue with both extensions, but was still able to login. I bet that it is not related to privacy badger because i blocked everything there and it still worked. AdBlock is a different kind of story because I do not know which blocklists you are using. It might be that one of the blocklists is too restrictive. Maybe you can find out which blocklist it is.

**Comment by dns2utf8** [comment]
I disabled the addons and tried again. The problem appears to be around mixpanel.

**Comment by dns2utf8** [comment]
I tried a login with all addons enabled in an anonymous session and it works like expected.
Is it possible that the local storage is corruped? Can I recover from that without loosing the history on the device?

**Comment by dns2utf8** [comment]
I was able to fix it, I cleared the cache but kept the LocalStorage, IndexDB, WebSql and Cookies:
![image](https://user-images.githubusercontent.com/739070/34846971-25293478-f71a-11e7-973a-5550206a55cf.png)

**Comment by gregor** [comment]
Thanks for the update and glad you are able to log in again.
