### ISSUE TITLE
wire-webapp Screen sharing interrupts Audio call

### ISSUE THREAD

**Issue by fdelapuente** [wireapp/wire-webapp#219]
Hi,

During a Call from the webapp in Linux/Firefox to an Android device, the moment screen sharing was activated in the Firefox endpoint, the audio communication got interrupted. The audio couldn't be recovered and a new call had to be made.

Let me know if you need more information.

Thanks.

**Comment by gregor** [comment]
Thanks for the report. We are aware of this limitation between desktop and mobile. Are you using screensharing from desktop to mobile regularly? Screen sharing was implemented as a desktop first feature and mobile clients have not caught up to the functionality yet.

**Comment by fdelapuente** [comment]
Hi @gregor,

Actually It's not critical for me, I'm just filing the bug to help the development/improvement of wire. Good to know it should be working in Desktop-to-Desktop communication (I haven't tried it yet and this is more important for me).

Best Regards.

**Comment by gregor** [comment]
@fdelapuente Yes, desktop to desktop screensharing works in all but one scenario. This is due to the different state of webRTC support implemented in Firefox vs Chrome. Specifically Chrome still misses the RtcRtpSender.replaceTrack() functionality and has to move from Plan B to Unified Plan SDPs. We currently opted to implement the standards conform way with results in no audio if you start screensharing during a video call from Wire for Windows/OS X. On Firefox this does work. It's fine if you "upgrade" an audio call to screensharing. You can track the state of the Chrome support on their [platform status](https://www.chromestatus.com/feature/5347809238712320)

**Comment by gregor** [comment]
https://github.com/wireapp/wire-webapp/pull/915

**Comment by gregor** [comment]
I am happy to say that the fix will finally be part of our next release,, which will reenable screensharing.
