### ISSUE TITLE
Wire forgot my device after Chromium update

### ISSUE THREAD

**Issue by fonixer** [wireapp/wire-webapp#2497]
## Wire for web version

2018-02-16-07-54-prod

## Browser version

Chromium (problem occurred after updating from 64.0.3282.140-1 to 64.0.3282.167-1)

## Operating system
GNU/Linux
## What steps will reproduce the problem?

1. Updating Chromium
2. Trying to log in on app.wire.com

## What is the expected result?
Wire recognizing my browser.
## What is the actual result?
Wire asks me to remove one of my devices in order to add a new one.

I updated Chromium and now Wire doesn't recognize my browser. Although, on the loading screen it knows my username (maybe it is in the cookies). 
IndexedDB is still in my .config folder.
I lost all of my chat history. I kept using this system installation and browser just to wait until chat history export feature will be available this year.
Now all is gone.
Is there anything I can do?

**Comment by max-baz** [comment]
My friend and I have also lost history during the past month, although both of us use desktop app. One day we start computer and Wire doesn't remember us and prompts to enter login/password.

I spend a little time trying to "migrate" IndexedDB, but gave up. I'm afraid there's nothing we can do besides hoping to see a history backup / restore feature implemented (#626).

**Comment by Bomper** [comment]
![image](https://user-images.githubusercontent.com/34669048/36712159-4768fd16-1b3c-11e8-9698-b69d9cd717c6.png)

I've also lost all my conversations.

For a web app, this is just NOT ACCEPTABLE. It's one thing to use a desktop client like Pidgin, which saves messages locally (on an encrypted drive, if the user chooses so), and a completely different one to not give the user their own messages.

What is the rationale for Wired protecting me from my own messages? What exactly are those "privacy reasons" from that screenshot above?

@wireapp developers, how would you feel if Protonmail deleted all your emails when you logged in from another device?

Seriously. For crying out loud, **this is my own content**. Why don't you let me see it?

Let alone that I'm tech-savvy user who can take care of my own encryption. I run Wire over a VPN and my browser data is stored on a Truecrypt drive.  Please don't treat me like the proverbial grandma.

I was a believer in Wire because it didn't go the silly "you must give your phone number because we want to make privacy accessible to the masses" route that Signal and other apps went to, but policies like this, and complete disregard for the fact that I was [unable to log in for almost two weeks](https://github.com/wireapp/wire-webapp/issues/2487), are turning me completely away from the product.

**Comment by gregor** [comment]
Plain and simple: Because we can't. Wire is an end-to-end encrypted messenger.

If you receive a message, it is targeted at your client as in the webapp you have previously logged in. We decrypt the message. For that we need the decryption session which is stored in the IndexedDB. The we store both in the IndexedDB again. If for any reason the browser storage is lost - which can happen when the browser makes a mistake, the oprating system clears files, you are low on dis space, etc - and you log in, we have no means to recover your messages. That is the whole point of end-to-end encryption.

Unexpected history loss is obviously unintended and painful, be assured that we understand your pain and continue to work fixing cases where the database is lost because of errors on our end and to improve the storage solution in general.

**Comment by gregor** [comment]
@fonixer Unfortunately there is not much you can do. If you browse your IndexedDB for app,wire.com within that browser and no longer see any databases or database content, you are unfortunately out of luck. We cannot do anything when your data is gone from the IndexedDB.

**Comment by gregor** [comment]
We haven't found the root cause for data loss. But with the history backup and restore feature we have shipped means to alleviate the situation at least a little bit. Since there is no information in this issue that will help us to get to the root cause of the problem I will go ahead an close this.
