### ISSUE TITLE
Inform users that their conversations can be lost forever

### ISSUE THREAD

**Issue by Bomper** [wireapp/wire-webapp#2576]
As @maximbaz stated in #626,

> nobody would use Wire if they [knew] that they might require to refer to this conversation history later — it's just too easy to lose it forever

I did not know this when I signed up for Wire, and indeed, I lost all of my conversations, along with others - #2497.

I don't find this acceptable at all. If this is a risk that users want to take in the name of privacy, fine. But I run Wire in a browser off a Truecrypt drive, and I prefer to save my conversations, so I can refer to them later. Please let me make the choice between Wire, and a messaging service that does preserve my conversations.

### When users sign up, there should be a prominent warning that their conversations can be lost by something as trivial as clearing their browser's data.

I was a believer in Wire because it didn't force me to give out my phone number to sign up, and I could use a much more reasonable email address. But policies like this, plus complete disregard for extended critical outages (I was [unable to log in for almost two weeks](https://github.com/wireapp/wire-webapp/issues/2487)), are turning me completely away from the product.

**Comment by gregor** [comment]
Thanks for the feedback that we will be reviewed by our product and design people. History loss due to storage loss in inherit with end-to-end encryption and is clearly detailed in all of our documentation. We will think about how to better explain and manage expectations of new users.

**Comment by Bomper** [comment]
> History loss due to storage loss in inherit with end-to-end encryption

I'm not a cryptography expert, but [that doesn't seem to be the case](https://security.stackexchange.com/questions/180722/is-loss-of-conversation-history-inherent-to-end-to-end-encryption). Also, how do end-to-end encrypted email services like Protonmail work? I don't lose all my emails if I log in from a new device.

**Comment by max-baz** [comment]
I'm not an expert either, but it is an interesting topic and I would be interested to see if my intuition is correct 🙂 And if I'm more or less right, the only reasonable solution would be a [client-side history backup & restore](https://github.com/wireapp/wire-webapp/issues/626).

Lie Ryan correctly pointed out that message loss is not crucial to end-to-end encryption per-se, but it is related to one of the two things (or a combination of the two): forward secrecy and per-device encryption key.

Simply put, with FS every message is encrypted with a new key that depends on the key of the previous message, thus you can only decrypt a message if you decrypted the previous message. For example, if someone hacks your account today, they can eavesdrop on your future messages, but they can never decrypt your past messages.

With per-device encryption keys, every message is encrypted with multiple keys, one for each device of the sender and recipient. When you introduce a new device, you basically create a new key, and thus you can only decrypt messages that were encrypted for this key. The clients will use your new key (new device) only to encrypt the new messages, but they will not re-encrypt past history (they could have, but it would be an extremely expensive operation).

My bet is that Wire is using a combination of the two, but I'm not sure. PGP is an example of E2E encryption with no FS and per-user encryption keys. Protonmail likely does not use FS and most certainly they use only one encryption key (they used to have two passwords, one for account and one for the encryption key), that's why they are not affected.

**Comment by Bomper** [comment]
@gregor: where is Wire fetching the conversations from when the user logs in?

![image](https://user-images.githubusercontent.com/34669048/37078670-1012cf22-2195-11e8-9164-f0c5c6d02d58.png)

**Comment by gregor** [comment]
It fetches conversation metadata not content. We need to know which conversation you are part of, which names they have, and who else is part of them. More of this kind of metadata is supposed to be removed from the backend but for now it is still there as detailed in our whitepapers. We do not and cannot fetch conversation history.
