### ISSUE TITLE
Random disconnects when running webapp locally

### ISSUE THREAD

**Issue by dschoepe** [wireapp/wire-webapp#306]
After running the webapp using `grunt` and logging in, the session will disconnect after some minutes of inactivity of the client with the message "Trying to connect. Wire may not be able to deliver messages". Incoming messages are still received, but it is no longer possible to send messages. The webapp does not manage to reconnect without logging in again.

(Only tested on the `prod` branch.)

**Comment by gregor** [comment]
This is due to CORS limitations. Running the webapp locally we will not be able to refresh the access token. The backend expects the request to originate from certain domains that are whitelisted. As of now the backend is not open sourced and we have no means to change this whitelist for security reasons. We need do that roughly every 14 minutes. As this fails. we try to log you out. One of the few other calls that are limited by CORS. Thus you get stuck in this reconnecting state. Currently nothing we can avoid.

But you can always start the Chrome browser with the `--disable-web-security` flag. Depending on the Chrome version and platform you are on you might also have to  set a separate `--user-data-dir="C:\ChromeProfile"` folder for the profile to be used. This will ignore the CORS check and we can properly refresh the access token. (or log you out or register an account for that matter)

**Comment by dschoepe** [comment]
I can confirm that running Chrom(e|ium) with --disable-web-security and a different data directory fixes the issue.
