### ISSUE TITLE
Entering `:p` followed by enter doesn't send :p smiley

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-webapp#3118]
## Wire for web version

`2018-04-09-10-16-prod`

## Browser version

Firefox Developer Edition 60.0b10 (64-bit)

## Installed browser addons

uBlock, HTTPS Everywhere (disabled), User Agent Switcher - not active

## Operating system

Fedora 27 64-bit (GNU/Linux)

## What steps will reproduce the problem?

1.  Type `:p`
2.  press enter

## What is the expected result?

The message ":p" is sent (with the input text box being empty after)

## What is the actual result?

The text input now says `:package`, nothing was sent off.

Edit: changed my mistake that `:P` actually works as intended, just `:p` doesn't

**Comment by max-baz** [comment]
The distinction between `:p` and `:P` is by design, semicolon with uppercase letters is used for emoji conversions (e.g. `:P` -> `😛`), semicolon with lowercase letters is used for selecting an emoji from the emoji dropdown.

Noting that, what you describe in the "actual result" sounds like a bug. Here's the expected behavior that I get in the desktop app:

![wire-emojis](https://user-images.githubusercontent.com/1177900/38762265-9ef5cccc-3f8a-11e8-8acb-f2da1de92d2c.gif)

**Comment by ghost** [comment]
@maximbaz then it's a design bug. `:p` is a common smiley, when I am not familiar with a messenger and I type that and press enter, it really should send ":p" and not do something unexpectedly different. If your current smiley picker interferes with that per design, then I really think you need to fix the design of your smiley picker. Nobody wants to use `:package` all the time, there is no need for that to be so easily accessible at the cost of interfering with a common smiley.

One way of doing this would be to add `:p` into your smiley picker list, and make sure it is the selected default after `:p` was just typed, and that pressing enter on the default if it was already fully typed out will also send the message instead of just closing the smiley picker popup. Maybe not the best solution, I'm sure someone else might have a better idea - just what I can come up with off the top of my head.

Just in case those are also broken (didn't test), the same really applies to all the other common lowercase smileys like `:x`, `:c`, `:b` and others I might not think of right now.

**Comment by max-baz** [comment]
The emoji picker is useful to those who want to use it, I wouldn't immediately scratch it as a design bug. And for what it's worth, it is designed to learn your favorite emojis and prioritize them in the list, so it will put `:package` as the first entry only until you actually start using this feature.

Judging by the issue description, you actually discovered by yourself that the supported way of getting 😛 is typing `:P` instead of `:p`, so I'd argue it's quite intuitive for new users - but having this properly documented somewhere would certainly be beneficial.

Finally, as soon as you type `:p` you should see an open dropdown menu with a selected entry, so it shouldn't be that unexpected that pressing Enter submits the selected entry in the dropdown.

**Comment by ghost** [comment]
> The emoji picker is useful to those who want to use it, I wouldn't immediately scratch it as a design bug. 

I haven't said the emoji picker is a design bug. I said that making way less common smileys more easily reachable at the cost of interfering with typing out the common ":p" should be considered a design bug.

> Judging by the issue description, you actually discovered by yourself that the supported way of getting stuck_out_tongue is typing :P instead of :p, so I'd argue it's quite intuitive for new users

Actually, I only found out because I told someone else about this bug, they told me "huh, works for me" and eventually we found out why. And no, having users run into a wall typing what they had *actually* wanted to type is not intuitive at all.  Don't make "features" interfere with typing common message choices - and again, I already suggested one (of possibly many) ways to integrate this without stopping people from typing the common default smiley choices. And first needing to teach the thing a reasonable default is not a proper solution either.

But that's just my opinion. However, I would be surprised not to find many who agree with me. (Unless maybe everyone types `:P` naturally instead of `:p`? I don't know, I don't have the numbers. But I certainly use `:p` a lot as well)

**Comment by ghost** [comment]
I type :c as a sad face emoji and run into this a lot because suddenly it's a cactus. It's probably not unreasonable to make colon only search for an emoji after 2 or so characters have been typed, as Discord does. This would enable people to easily type most short emoticons without constantly having things change as soon as they hit enter instead of sending their message.

**Comment by max-baz** [comment]
This was considered, but there are emojis whose name consist of one letter only (e.g. `:a`), to make the autocomplete work for all emojis the decision was made to rely on letter case (lowercase for emoji autocomplete, upper case for text emojis or emoji substitution).

**Comment by ghost** [comment]
What about only doing this for those emojis then? (whitelist for an early trigger just for those emojis)

**Comment by max-baz** [comment]
It would conflict with the "commonly used emojis" functionality, e.g. for me when I type `:c`, I get `:cry` and `:confused` as the first two entries (because I used them), so it is very convenient to type `:c<Enter>` or `:c<Down><Enter>` to send those again. Same for `:p`.

I can see how this can be confusing if you don't know about lowercase/uppercase difference (and Wire could do something about it, show this as a hint somewhere in UI or explain on their website; I also proposed a while ago to prepare a guest post for their blog on Medium to explain everything about emojis, from how to use them to why certain decisions were made and how Wire is probably the very few apps that truly follows Unicode standard at rendering emojis... but we never followed up on this).

But I'd like to understand, once you _know_ the difference between lowercase and uppercase letters for emojis, is there anything beyond an inconvenience to get used to this convention? It could take an effort to get used to a new convention, but if you take all currently supported scenarios into account, I truly believe this is the case where the benefits outweigh the cost of getting used to typing textual emojis in capital letters.

Also, not suggesting as a workaround, but just for the sake of completeness: on a rare occasion when you need to send `:p` as a text, you can do so by typing `:p<Esc><Enter>`.

**Comment by ghost** [comment]
> But I'd like to understand, once you know the difference between lowercase and uppercase letters for emojis, is there anything beyond an inconvenience to get used to this convention

Yes, it's called muscle memory. *Not a single other messenger I use does this.* (facebook web messenger, threema web, empathy and pidgin xmpp messengers, telegram desktop messenger) Not one of them!

This means while `c:<enter>` turning to `:cry:` is useful for the select few people that mainly use Wire, for everyone else this shortcut isn't really feasible to learn because once you get used to it, it'll infuriate you everywhere else. Similarly, I've used and learned `:p<Enter>` to send ":p" over many years in all other messengers, and more importantly, *it still does that today* (while it will send `:package` precisely nowhere).

People aren't good at learning *conflicting* super short shortcuts in different programs they use - it's just a horrible idea.

Edit: oh and I type `:p` on Wire for android as well, where it works perfectly fine and sends ":p" as in 99% of all other chat clients.

Edit 2: interestingly, GitHub uses this system. Is that where you got it from? It's honestly the first other application where I've ever seen this and I've never noticed it there, simply because on GitHub I rarely use smileys at all.

**Comment by ghost** [comment]
Wait, you say conflict with commonly used - why not add `:c` and `:p` as smileys into the dropdown then? Since I never use any of the others, that seems like it would work fine. Or is there a reason you can't add additional smileys to it?

**Comment by max-baz** [comment]
> Yes, it's called muscle memory. Not a single other messenger I use does this. (facebook web messenger, threema web, empathy and pidgin xmpp messengers, telegram desktop messenger) Not one of them!

What I meant is that although it is inconvenient to change habits, all of those apps understand `:P`. And as far as I know the mentioned apps don't have as feature-rich autocomplete, and we should consider that maybe the reason that they allow lowercase letters is because they don't have to support as many features, and/or don't allow searching for a full set of available emojis (such as `:a`). Progress moves forward, reasonable sacrifices have to be made.

> why not add `:c` and `:p` as smileys into the dropdown then? 

This is an interesting idea.

Wire uses [this list](https://github.com/emojione/emojione/blob/master/extras/alpha-codes/eac.csv) as a source of emoji names (`alpha code` column), and there are no existing entries for `:c:` or `:p:` in that list, so we could have added these two. Because the emoji popup is alphabetically sorted by default, `:c` and `:p` would even be the top entries in it.

There are two downsides to this approach:

1. You'd have to type `Enter` twice, first time to select the entry from the popup, and second time to actually send the message. But I guess that's expected.
2. Not all emojis can be added, for example `:x` and `:o` exist as single-letter emojis in the list. And if the next version of emojis adds `:p`, we would have to remove the "`:p` as 😛" and add "`:p` as \<new emoji\>", which would be even more damaging to users (it used to work, but with the update it stopped).

**Comment by ghost** [comment]
> What I meant is that although it is inconvenient to change habits, all of those apps understand :P.

Fair enough. But I've had ten years of typing `:p` and I use Wire only occasionally (for one person actually, while for the other >20 people I use different ones). Even if I wanted to type `:P` always, I don't think I could reasonably teach myself at this point, unless `:p` stopped working everywhere. But sure, if it's only me with that problem, that's fine - I realize Wire is not made for me as a single person talking to a single other person.

However, from the others commenting on this ticket, I assume I might not be the only one - but obviously, I don't have any numbers.

> You'd have to type Enter twice

Yea okay, that's similarly going to throw people off. I suppose in that case it's not a good idea either.

**Comment by gregor** [comment]
Thanks for the detailed discussion on our emojo feature that was mostly implemented as a contribution by @maximbaz. We have no immediate plans to change the current behavior as specified. As we do not consider this a bug I will go ahead and close the issue at this time.

**Comment by ghost** [comment]
I recommend you consider a user survey at some point. I kind of doubt many people rely on `:p` or `:c` showing up the popup (vs e.g. after two letters) while from the comments you can see I'm at least not the only one that is actively *bothered* by it - but of course I don't know the numbers, and I assume neither do you. Might be useful to shed some light on whether it's useful to reconsider the design here or not.

**Comment by ghost** [comment]
Just an update, I still run regularly into this. Somehow can't believe I'm the only one... (and not once I wanted to actually type `:package:`, I'm sorry,...)

Any plans on a user survey or something? Do you have any sort of framework or checklist for doing some basic UX tests with users? I feel like this would be a really useful opportunity for something like that.
