### ISSUE TITLE
Report version in webapp

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-webapp#371]
Full version should be reported in webapp, just like desktop version.

**Comment by gregor** [comment]
Can you please elaborate your request? I do not understand what you are asking for.

**Comment by ghost** [comment]
Desktop version Help → About Wire reports version (e.g. 2.11.2665), same in `app.wire.com` just reports 2016-10-26. For bug hunting purpose it would great to have comparable version naming.

Also underlying JavaScript libraries should be mentioned somehow (e.g. image processing JIMP).

**Comment by gregor** [comment]
Check the top of html code at app.wire.com.  Within a comment you will see full version string, which is a timestamp that also contains the hour and minute. We use those as the release tags on github to identify releases.

**Comment by ghost** [comment]
OK, it is clear, not within GUI, but OK. Then logical question to ask is about desktop version. Like mentioned above 2.11.2665.

My idea was about uniform version information.

**Comment by gregor** [comment]
They are completely separate. We need a version number in the above scheme for the Apple AppStore. We don't really have major, minor version on the web. We just release - usually once a week, sometime in between and sometimes not for two or three weeks. Dates is what best reflects this. The wrapper then makes use of the new webapp whenever it is available and you next restart or trigger a page refresh on another way. We do not need an app update via the AppStore on macOS or the background in app updater on Windows in order to release new features to the desktop version. Most of them do not require any changes to the app code but only on the web app side of things.

**Comment by lipis** [comment]
Do you mean this one maybe?
<img width="549" alt="screen shot 2016-10-29 at 16 51 19" src="https://cloud.githubusercontent.com/assets/125676/19830416/09e31cc8-9df8-11e6-881b-81c9cbd9458c.png">

**Comment by helenakos** [comment]
Update to About screen is coming out in upcoming Wire for desktop releases. 
![screen shot 2017-04-11 at 14 57 39](https://cloud.githubusercontent.com/assets/5180637/24910197/4d87d612-1ec7-11e7-9135-c5e1a9214f22.png)
