### ISSUE TITLE
Import from Gmail not working in Rambox

### ISSUE THREAD

**Issue by keunes** [wireapp/wire-webapp#4116]
## Wire for web version

2018-07-16-14-05-prod

## Browser version

Installed Rambox v 0.5.17, Gmail gives me the following in their 'provide feedback' option:
appCodeName: Mozilla
appName: Netscape
appVersion: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Rambox/0.5.17 Chrome/59.0.3071.115 Electron/1.8.4 Safari/537.36
userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Rambox/0.5.17 Chrome/59.0.3071.115 Electron/1.8.4 Safari/537.36

## Operating system
Ubuntu 16.04

## What steps will reproduce the problem?

Clicking on 'import contacts' in Wire in Rambox, which opens a Google authentication page in my default browser (Firefox). After logging in to Google, I get stuck on a Google page saying 'One moment please'.

**Comment by gregor** [comment]
Thanks for your report. Rambox opens all external links outside its closed app scope. We do not support Rambox. In order to make the contact import feature work within our own desktop apps (which are also based on electron) we have to catch the redirect and handle it manualy within the electron context. Nothing we can add in Rambox. You will have to sign in at https://app.wire.com and import your contacts from their or install our own desktop apps available at https://wire.com/download.
