### ISSUE TITLE
Initialization of screen sharing blocks audio

### ISSUE THREAD

**Issue by max-baz** [wireapp/wire-webapp#4454]
## Wire for web version

Wire for Web Version 2018.08.22.0738

## Browser version

Wire for Desktop

## Installed browser addons

N/A

## Operating system

Arch Linux

## What steps will reproduce the problem?

1.  Start an audio-only 1:1 call
2.  Enable screen share

## What is the expected result?

Audio is not interrupted at any point of time

## What is the actual result?

While screen sharing is initializing (black screen), audio is interrupted, people cannot hear each other.

## Additional info

~~This bug is not present when it is an audio-only group call, audio is not being interrupted at any point of time.~~

**Comment by gregor** [comment]
@maximbaz Thanks for the report. Let me start by adding some technical explanation to the behavior you are seeing:

When we upgrade a call from audio-only to audio/video, the WebRTC `PeerConnection` has to be renegotiated in order to enable the new media type. Due to incompatibilities between Chrome, Firefox, and our own implementation on the mobile clients (unified vs plan B eg), we do not renegotiate the existing `PeerConnection` in this case but completely throw away the current call and connect a new one. As we are doing in above order this obviously causes the audio to interrupt.

I am surprised to hear that you do not see this in group calls. Technically it is the same. A group call is a set of 1:1 calls in a group as we are using a mesh solution to ensure foll e2e encryption. The audio should interrupt just like does in a 1:1 call. Due to the delay of encrypting the signaling messages sent via our backend for a potentially higher number of recipients, the delay should actually be longer. Are you sure this does not happen on the receiver side?

Obviously there is room to improve the experience. One idea would be to allow setting up two `PeerConnections` between the same people and running them in parallel or handing over once the new connection is established. The decision not to renegotiate the existing `PeerConnection` but throw it out and start from scratch came too late in the implementation process in order to change other assumptions we had made. We have been investigating many options on how to improve the UX but have yet to commit to or implement one of them.

**Comment by max-baz** [comment]
You were right, I just tested carefully, it does reproduce in group calls. It seems I simply didn't notice this yesterday.

Thanks for the explanation, it is interesting to read 🙂 Regarding the idea of two parallel `PeerConnection`s, do you mean one dedicated for audio and one for screen sharing? Just curious, what about video part of the call, would that need to run on a third `PeerConnection`? Because video can be enabled later in the call.

The reasons for not renegotiating the existing connection are clear, to me having two/three dedicated `PeerConnection` sounds like it is probably is the cleanest approach 🙂 Would be curious to know what you end up implementing once you get to this task.

**Comment by Aikatsui** [comment]
wireapp/wire-desktop#3709
#7018
https://github.com/wireapp/wire-webapp/issues/6156

**Comment by bennycode** [comment]
Hi @maximbaz, over the past 2 years we have massively shortened our call setup times and media request upgrades. 

In our current [release candidate](https://github.com/wireapp/wire-webapp/pull/9485) build, we don't have the problem of interrupted audio anymore when upgrading from an audio call to a screensharing session.

By now our calling implementation is also based on a [WebAssembly package](https://github.com/wireapp/wire-audio-video-signaling/tree/master/wasm) which is developed by our dedicated audio team. So we're using the same code on the web that we use in our native mobile apps.

We hope you like our next release!
