### ISSUE TITLE
Feature request → Escape UTF-8 symbols conversion

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-webapp#450]
Is it possible to make automatic conversion of escaped sequences in URL?

E.g. convert https://ru.wikipedia.org/wiki/%D0%97%D0%B0%D0%B3%D0%BB%D0%B0%D0%B2%D0%BD%D0%B0%D1%8F_%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0 to https://ru.wikipedia.org/wiki/Заглавная_страница

Thanks in advance.

**Comment by herrmannplatz** [comment]
👍🏻

**Comment by ffflorian** [comment]
Actually I wouldn't consider this a bug since this is the normal behaviour when you copy a link with UTF-8 chars from a browser address bar and paste it somewhere. I'm not aware of any app which converts this on paste and wouldn't implement it because sometimes you want to write something like `%80`.

But it would be a nice improvement to convert these URLs after sending them.

**Comment by herrmannplatz** [comment]
Sry, i think i misunderstood the question. As ffffflorian pointed it out there are cases where this would actually break the url.

**Comment by ghost** [comment]
As far as I understand this conversion is fully reversible and will not break anything. Browsers do this conversion for quite a long time already.

**Comment by ffflorian** [comment]
OK I think I didn't make myself completely clear.

Yes, in the case of a URL the conversion is useful and won't be a problem. But what I meant is, that I would convert `%80` only to `р` (cyrillic letter `r`) when it's actually a URL and only *after* we sent the message containing the URL. Then the URL preview is added anyway and the UTF-8 codes could be converted, too.

Because if we convert the URL immediately after pasting, the user will be confused why the content changed (e.g. if a URL with escaped characters – in this case `%80` – was copied). Also IMO it's in general not a good idea to alter the user's text, even if we think it's a good idea.

Another example: I have a text which contains `10%80` – e.g. to paste JavaScript code with the [remainder operator](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Arithmetic_Operators#Remainder_()):

```js
var x = 10%80;
// x = 10
```

I don't want this code to be converted to `var x = 10р;` :wink:

**Comment by ghost** [comment]
**First:** `var x = 10%80;` should never be treated with URL processing code since it has got no scheme identifier.
**Second:** Browsers already do this conversion and few people are confused. I'd say that I more confused to have escaped URL in buffer, because I copy "normal" URL in browser and then I get escaped sequences in Wire.

**Comment by max-baz** [comment]
It is annoying, but it is a browser issue. Copy URL and paste it _anywhere_, and you will see these `%` signs.

A quick search found [one bug report](https://bugs.chromium.org/p/chromium/issues/detail?id=68718) for Chromium, but it seems to be closed as Won't Fix. I personally think if you want this issue to be _properly_ fixed, raise this issue again on the browser's issue tracker.

In meanwhile there is a workaround: you can copy the URL without the scheme part, and it will not be encoded with `%`.
