### ISSUE TITLE
Chat history synchronization 

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-webapp#473]
I'm sure I don't get something in concepts of Wire, but anyway. Why I cannot get chat history synchronized on newly added device even if it was marked as verified in settings?

Thanks in advance.

**Comment by ffflorian** [comment]
**Short answer**: For privacy and encryption reasons. This doesn't have anything to do with marking another device as verified and is intended behaviour.

**Longer answer**: All sent messages are encrypted for all your current devices. When you add a new device, your old messages are not encrypted for your new device and can't be re-encrypted because your new device never saw those messages unencrypted (also the other devices won't re-encrypt them because it would take too much time and would break the privacy concept).

**Complete and complex answer**: [Read the Wire Security Whitepaper](https://wire.com/resource/Wire%20Security%20Whitepaper/download/) (`4.1 End-to-end encryption`).

**Comment by ghost** [comment]
OK, clear. Thanks for comments!

**Comment by ffflorian** [comment]
Alright, could you close this issue then? Thanks!

**Comment by lipis** [comment]
Thanks @ffflorian for clarifying it. If you have more questions/issues @timur-davletshin don't hesitate to open another issue :)
