### ISSUE TITLE
Improve message reply UI

### ISSUE THREAD

**Issue by v0s** [wireapp/wire-webapp#5176]
## Wire for web version

2018.11.15.1314

## Browser version

Wire Desktop v3.3.2868

Thanks for adding message replies to Wire! I have a few minor suggestions about the UI, based on Telegram messenger which has a nice and well-thought interface.

## Message reply shortcut

Currently Wire provides a message reply option in "..." menu next to the message. 

![Wire reply button demo](https://img.vos.uz/iv104y09.gif)

Telegram has a handy shortcut that can be ported to Wire as is: double-click on the message row, but not on the text itself.

![Telegram reply shortcut demo](https://img.vos.uz/9n1n7oqs.gif)

## Jump to original message shortcut

Currently Wire shows an "Original message" link for every message reply. 

![Wire jump to message link](https://img.vos.uz/lqqsc95o.gif)

Telegram jumps to the original message with any click on the reply label, including on original sender's username. 

![Telegram jump to message shortcut](https://img.vos.uz/ae68pmo3.gif)

I also think 'Show more' link in Wire is superfluous, because there already is one click leading to the full original message.

## ***

Since message replies are really helpful for large group chats, i think UI improvements would be appreciated by many users and immerse them into using Wire.

**Comment by jennifergoertzen** [comment]
Hi @v0s,

@bennyn passed along your feedback to me. I’m on the design team at Wire.

Before I jump in, thank you for taking the time to write this out and include examples from both apps. It’s awesome to have a piece of software that not only do people use but they care enough to help it become better.

### Message reply shortcut

The shortcut in Telegram is a great way to reply faster. We’re looking at adding shortcuts in future iterations of the reply feature. For the first version, we focused on making it visible in the UI so more users would find and use it. Now that the functionality is becoming part of how people speak in Wire, we’ll look for ways (like double-clicking) that are less visible but quicker.

### Jump to the original message shortcut

Telegram’s clickable quote gives a larger click target, but we found that it also reduced some other functionality within the reply.

In the Wire browser version, you can interact with the content of the original message where it is quoted—rather than always sending the user earlier back in the conversation. This is important for messages that contain images, videos, files, links, or locations.

You can also click the original sender’s name to view their profile. This is helpful in the case of large teams where you may not be familiar with every participant of a conversation.

### "Show more" link

We made the choice to include a “show more” link for the times when you don’t want to return to the original message. In our research, people would often reply to messages much earlier in the conversation. When reading a reply, it was common to want to read the content of the original message where it is quoted, not in the original place in the conversation. Having a “show more” link means I don’t go way back in a conversation and then need to return to where the quote appears to read the reply itself. I can read everything in one place.

***

Thank you again for sharing your feedback. We are continually iterating on what we create although we may not be able to double-back and make changes immediately. Please let us know if you have any further suggestions—we really appreciate all the feedback.
