### ISSUE TITLE
1-day timed messages disappearing after 1 second

### ISSUE THREAD

**Issue by dbquarrel** [wireapp/wire-webapp#5388]
Wire version: 3.3.2862
Wire for web version: 2018.09.28.1146
Operating system: macOS 10.12.6 

What steps will reproduce the problem?

Cannot easily replicate. It might have to do with time zones between users being 12 hours separated but this is only a guess. Happens both on iOS versions and on macOS versions, doesn't matter which.

What is the expected result?

Message should expire after 1 day.

What is the actual result?

Message expires after 1 second (not sure if it is the expiration causing the message deletion or something else).

Please provide any additional information below. Attach a screenshot if possible.

**Comment by kacperpaczos** [comment]
I can't reproduce It.
Wire version: Version 3.3.2872
Wire for Web Version 2018.10.15.0814
Operating system: GNU/Linux

**Comment by dbquarrel** [comment]
As an update this is happening with all my contacts now rather than just one.

**Comment by ghost** [comment]
Still happening to me regularly as well along with a log-in bug now. It's very frustrating and feels like since WirePro the regular version has been left behind as bugs increasing. Looking for alternatives now as regular bugs are getting on everyone of my contacts nerves to the point they dont want to bother using it.

**Comment by dbquarrel** [comment]
If anything it is worse now for me. This is happening many times a day 
and I've had to work out a protocol with my contacts about not repeating 
to me that the message disappeared as I can see it disappear too and 
that I already know I have to type up my message again.

To me the overall thrust is clear.

UI candy and toys that look good on advertising is being prioritized 
over system and data integrity. This is dealing with a rusting out frame 
by putting a coat of paint on it and pretending it is not there.

That means the focus is only on flash that will attract new users, and 
little focus is given to maintaining a reliable system for existing users.

Does this same attitude carry forward into the security and encryption 
aspect? Is dark mode more important than security and data integrity? I 
think most serious users will say no. But the marketing department says yes.

When the marketing department is working off of a different script, that 
is:

1. increase user base
2. increase value of the company
3. sell the company to a bigger company
4. everyone gets rich

This is not anything a serious user will want to put faith in. A product 
that is built on smoke and mirrors in order to fake out a bigger company 
into buying it out has no future. That means for the existing user base 
that we need to constantly have our ears open for a better product. 
Since everyone is working off of the same business plan, to get eaten by 
a bigger fish, this means the users have to suffer through finding the 
"least bad" solution.

I wish I could promote this product as a great product, but this is an 
ongoing problem of simple major issues being ignored (the years of 
wailing on the CPU while nothing is happening is another example of this 
lack of care about basic core issues in favor of UI baubles).

Someone should care and fix this.

But, seems that it is just not important that a MESSAGING SYSTEM deletes 
MESSAGES. To me that is an issue that is a core issue. It would be like 
Photoshop erasing images, or Word deleting files. Your core mission is 
failing and this bug was reported long, long ago. That means there has 
only been trivial attention given to it. It's not acceptable to fail at 
your core mission and expect to be a successful product.

Like Fyre Festival, there is only so long you can surf on pretty images. 
Core mission failures that are completely visible are like the one 
cockroach you see. If the company doesn't care about visible core 
issues, what care do they give to those that are not visible on the 
surface? The answer probably is "if the users cannot see it, then it 
doesn't matter, we want to grow the user base and sell this so we just 
need more shiny chrome on front to get more people in."

Again, horrible optics at the very best. Symptoms of rot at the worst.

**Comment by ghost** [comment]
I imagine they are just allowing it to rot to drive people to Pro and shed anyone who isn't willing to pay. This is how it ALWAYS goes even when companies say they "would never do that". There have been periods of maybe weeks at a time things have MOSTLY worked for me but never more than that. There is always SOMETHING messing up like notifications stop coming randomly, messages wont deliver for a whole day, "decrypting" hangs for 30mins one day out of a few or something. Seeing how most bug reports across the platforms have been ignored without a single comment tells me its not going to change. Like you I had "workarounds" where I would SMS someone to tell them to get on Wire because we couldn't rely on consistent notifications and I would often find "didn't see this for two days" sort of replies.

I'm not averse to paying for a service but it has to work...and I wouldn't be able to convince anyone else to pay for it given their experieces so far. It's a real shame since its the only multiplatform option...even Signal is less suitable because it requires phone number and linked mobile account. I am looking for a replacement but cannot find anything that does calls/video/files etc and works on all platforms including linux and browsers.

**Comment by bennycode** [comment]
Bug has been fixed.
