### ISSUE TITLE
Blank Log-In page on Firefox

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-webapp#5754]
*Nevermind. Bugs are not addressed and getting worse so giving up on Wire. The promise to never leave the Personal branch behind in favor of an Enterprise product has been broken like every other project that says that. My fault for falling for it again. The Personal account sign up has even been buried on the website using dark patterns so people likely won't even know it's an option were they willing to put up with the buggy mess.

**Comment by ffflorian** [comment]
@hap124 Do you see any error in the Firefox console?

**Comment by ghost** [comment]
____________________________

**Comment by ghost** [comment]
____________________________

**Comment by ffflorian** [comment]
Hi @hap124,
thanks for the log - unfortunately we can't read much out of it.

Could you open https://www.useragents.com/ with your Firefox and copy-paste the output here? That would help us. Thanks :slightly_smiling_face:

**Comment by ghost** [comment]
____________________________

**Comment by danila-io** [comment]
I have the same issue quite frequently these days. It often displays a blank page for about 5-10 minutes and then finally loads the page (sometimes it fails). 

The problem is not specific to Firefox (Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0 ). Epiphany simply fails to load a page saying that this browser is not supported (more than 5 minutes waiting time) (Mozilla/5.0 (X11; Ubuntu; Linux x86_64) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Safari/605.1.15 Epiphany/605.1.15). I have attached a screenshot of Epiphany trying to load the page.

I also see this white screen for 5-10 minutes in the desktop app on macOS (Mojave 10.14.4)

UPD: 
Here's the error message I get in Firefox:
Corrupted Content Error
The site at https://app.wire.com/ has experienced a network protocol violation that cannot be repaired.
The page you are trying to view cannot be shown because an error in the data transmission was detected.
Please contact the website owners to inform them of this problem.

Log in Firefox: Failed to load ‘https://app.wire.com/’. A ServiceWorker passed a promise to FetchEvent.respondWith() that rejected with ‘TypeError: NetworkError when attempting to fetch resource.’.
![Screenshot from 2019-04-10 16-39-09](https://user-images.githubusercontent.com/23265002/55879743-61852c00-5bb0-11e9-97ca-8ffb45b1de94.png)

**Comment by codawithacurse** [comment]
I am having the same issue but mine never loads, just a blank page. Errors I see in Firefox console are:

Navigated to https://app.wire.com/
Content Security Policy: Couldn’t process unknown directive ‘prefetch-src’
TypeError: navigator.mediaDevices is undefined
Environment.js:147:6
    <anonymous> Environment.js:147
    Webpack 10
        f
        <anonymous>
        <anonymous>
        f
        <anonymous>
        <anonymous>
        f
        t
        r
        <anonymous>


Any updates?

**Comment by ghost** [comment]
____________________________

**Comment by lambdadog** [comment]
I've had this issue about a year on and off, but it seems worse lately, although I'm not a frequent user anymore since I've just decided to move to my own XMPP servers

**Comment by danila-io** [comment]
Just a quick update: I haven't encountered this issue since writing about it here back in April. Whatever it is, it's a bit hard to trigger.

**Comment by ghost** [comment]
____________________________

**Comment by ghost** [comment]
____________________________
