### ISSUE TITLE
Feature request: option to show sender's name in notifications, but not the message itself

### ISSUE THREAD

**Issue by max-baz** [wireapp/wire-webapp#586]
Having the ability to hide all information about the incoming message in a notification is good, but there are cases when a user would like to see who is the sender of the message, while not exposing the message itself.

To see the sender's name allows a user to have less distractions when they are busy with something else, a user now is able to make assumptions whether the message is important and perhaps worth the distraction, or it is rather a not-important matter which could easily be taken care of later.

I'd like to offer to prepare a pull request for this feature, but I would require assistance in preparing the text for the new option in settings, plus all the translations for it. Let me know if you would like me to work on it.

**Comment by gregor** [comment]
I thought about this when implementing the feature a little while ago. In the end together with our design team we decided against it to simplify implementation and testing effort in order to release quickly, as this was some sort of a side project. I will talk to design on Monday if we want to enable the more granular approach you are offering to implement or whether it ads too much complexity from a user experience perspective and get back to you.

**Comment by gregor** [comment]
Somewhat related when looking at this again: https://github.com/wireapp/wire-desktop/issues/234

**Comment by gregor** [comment]
@maximbaz I talked to our design team and we will be more than happy to accept a PR for this. We are looking forward to your contribution and I will help out wherever I can. Please keep in mind that merging and testing might be delayed due to the season though.

**Comment by max-baz** [comment]
Amazing news!

**Comment by max-baz** [comment]
Closing per #595.
