### ISSUE TITLE
Huge issues with wire on multiple clients (since today)

### ISSUE THREAD

**Issue by roberdorfer** [wireapp/wire-webapp#612]
Is there something wrong with the server? I've had a lot of problems today.

- Messages on the desktop client are not being sent (appear greyed out)
- Messages on the android client are stuck in "sending"
- Play button for voice messages on the desktop client is missing
- Images sent from ios don't show up on the android client
- Images that were sent don't show up on the desktop client or only show up very late
- The desktop client can't be closed the normal way but instead needs to be force-closed ( `killall wire` doesn't even work, instead you need `killall -9 wire` to close it)
- After killing wire a few minutes ago I can't log back into it because after entering my password and account name, nothing happens

**Comment by max-baz** [comment]
I confirm. By the way, it would be nice to have some analog of https://status.slack.com/ for wire.

**Comment by helenakos** [comment]
@rbieb Hey, thanks for the list. We're aware of the issues and are investigating. 

Can you tell me what do you see when you try to login?

**Comment by max-baz** [comment]
Can't speak for @rbieb, but for me and my contacts all the issues were gone around midnight on that same day.

**Comment by helenakos** [comment]
@maximbaz Yes, we had some issues that day. Most are resolved.

**Comment by EgbertW** [comment]
Not sure if this has influenced me or that it were separate issues, but I sometimes experience similar issues.

It would be great to have better self-diagnosis in the apps so that it actually detects when there are issues and warns the use that Wire is unavailable due to issues on the server, rather than appearing to work but misbehaving. I think it's better to have the app state "Sorry, Wire doesn't work at this moment, we're working on a solution", then appearing to work but actually don't.

**Comment by helenakos** [comment]
@rbieb Are you still experiencing these issues?

**Comment by roberdorfer** [comment]
Nope. It was only on that day, as far as I remember.

**Comment by helenakos** [comment]
@rbieb Yeah, that was the only day. I will close this one.
