### ISSUE TITLE
Desktop/Screen sharing not possible without microphone

### ISSUE THREAD

**Issue by thenktor** [wireapp/wire-webapp#6156]
On a PC without microphone/webcam it is not possible to use desktop/screen sharing because first starting a call is mandatory.

## Wire for web version
version="2019-03-18-12-58"

## Browser version
Firefox 66
Chrome 73

## Operating system
All

## What steps will reproduce the problem?

1.  Join Wire conversation on a PC without microphone
2.  Try to share your screen

## What is the expected result?
Share the screen without starting a call first

## What is the actual result?
You cannot share the screen because you cannot start a call first

**Comment by Aikatsui** [comment]
#7018 #4454 #6282 #7083 #6837 https://github.com/wireapp/wire-webapp/issues/8036
wireapp/wire-desktop#3709
wireapp/wire-desktop#2703
wireapp/wire-desktop#3735
wireapp/wire-desktop#3472

**Comment by thenktor** [comment]
Is this still an issue?
Without having this fixed sadly it is a waste of time to try Wire for business use again.

**Comment by bennycode** [comment]
> Is this still an issue?

Starting a call without a microphone is not possible in our UI. To still be able to share your screen you can ask the other party to start the call, so that you can join it with the PC that does not have a microphone connected. After joining a call you can then share your screen (even without having a microphone).
