### ISSUE TITLE
Feature request: ability to zoom images

### ISSUE THREAD

**Issue by max-baz** [wireapp/wire-webapp#698]
Click on an image - it is opened in full screen, with title and actions Download / Like / Delete.

What I'm missing is the ability to zoom the image in and out, in order to look at some detail.

Suggested triggers:

- Ctrl + mouse scroll
- Pinch zoom gesture

**Comment by gregor** [comment]
Thank you for your suggestion. That would definitely by a nice addtion. I hope we get to it at some point in the future. Will probably take a while though.

**Comment by bennycode** [comment]
Could be done with the [Pinch Zoom gesture](http://hammerjs.github.io/recognizer-pinch/) from [Hammer.js](http://hammerjs.github.io/).

**Example**
- http://codepen.io/naradesign/pen/GpXmVP

**Comment by mohammadrafigh** [comment]
Pinch gesture in hammer.js only works on mac and windows (in some devices and some driver implementations) and not linux (at least on my machine). I suggest to only stick with a simple scroll or as @maximbaz mentioned using ctrl+scroll

**Comment by bennycode** [comment]
We need to skip this issue for now. But maybe we will come back to it at a later point in time. 🙂

**Comment by Termuellinator** [comment]
not being able to zoom is my biggest issue with wire, so i'd be glad if this is implemented ^^

**Comment by cardassian-tailor** [comment]
I must say, the effects of the current implementation should, IMO, be viewed as a bug because it violates what the user expects the application to do. 

When viewing an image that has been shrunk to fit within the window bounds - the user expects that click to show the image either in a zoomed state, or in another window that permits zooming. Neither of that occurs here. The implied suggestion, I suppose, is to download the image in the image handler then zoom if you want. It's a poor UI implementation, though possibly an understandable decision depending on what else was on the plate and being dealt with at the time.
