### ISSUE TITLE
[Web] Missing Button for Emojis

### ISSUE THREAD

**Issue by rehoehle** [wireapp/wire-webapp#7014]
Is it correct that the Emoji button is visible in all other apps but not in the Desktop app? I couldn't find any Issue that described that. But it would be cool if the GIFs and normal Emojis would be available in the desktop client.

**Comment by ghost** [comment]
People who use Linux can download gnome characters. It works well with wire.
https://snapcraft.io/gnome-characters

**Comment by bennycode** [comment]
We don't plan to add a dedicated emoji button in our UI, please use the keyboard of your OS to insert emojis: https://support.wire.com/hc/articles/360000345958

**Comment by Aikatsui** [comment]
> We don't plan to add a dedicated emoji button in our UI, please use the keyboard of your OS to insert emojis: https://support.wire.com/hc/articles/360000345958

@bennyn It's necessary to reopen this FR unless wire intend to keep 20th century communication application however we don't interest to use that platform even for business environment but only encryption.

Consider let users to import custom static & animated emoticons/stickers as user mentioned above because we cannot expect wire may spend time for design some dozen of sticker packs. Such feature also available on telegram.

How we see and feels about wire applications today.
![Screenshot from 2020-09-02 04-53-45](https://user-images.githubusercontent.com/63988538/91911984-62a28600-ecdc-11ea-943f-66bff500b0a7.png)
Credits: @lulzlabs

**Comment by pYFZOS5** [comment]
https://github.com/wireapp/wire-android/issues/1925

**Comment by Luc45** [comment]
@bennycode Why not remove it from all other platforms such as mobile, for consistency?

I'm being ironic, I'd like this feature on Desktop, as well.
