### ISSUE TITLE
[Web] Reset all sessions at once. (very tedious when changing hardware)

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-webapp#7016]
We have groups with 200 people, I changed hardware and now everyone is complaining their's not getting my messages.

Is there any way to not have to click reset session for all +200 of my wire contacts?

**Comment by Transisto** [comment]
it's so bad, not only do I have to reset session with everyone I have to reset for all of their devices.

**Comment by bennycode** [comment]
@Transisto if you have broken sessions with 200 contacts then not being able to reset all sessions at once is not your biggest problem. We recommend you to create a completely new client in that case to have fresh cryptographic key material. Resetting a session is (and should be) an exceptional case, that's why we did not add bulk operations to our UI for it.
