### ISSUE TITLE
[Web] Allow desktop Wire client to make call or answer voice/video calls even no camera, microphone on the device

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-webapp#7018]
#### Allow Wire Desktop application to make or answer audio and video calls even no camera, microphone on the device or disabled access to them
 That is especially fever for desktop computer users or at any *urgent time(emergency), *hardware failures regardless desktop computer or laptop etc.

#### Regarding the notification message
   While client application allows to make or answer both video and voice calls as mentioned above then the notification able to set for display as optional similar below
_"Wire doesn't have access to your camera/microphone. End user(users) will not be able to see you or hear your voice. 'read support article' to find out how to fix it._

-------------------------

![screenshot_2](https://user-images.githubusercontent.com/46082456/52108234-d6297080-262b-11e9-85f9-f15d0ff2789c.png)

-------------------------------------

![52107943-f278dd80-262a-11e9-8404-c2f7729a3099](https://user-images.githubusercontent.com/46082456/61946868-dba9b700-afcd-11e9-95cc-f18076ed0227.png)

**Comment by ghost** [comment]
https://github.com/wireapp/wire-desktop/issues/2899

**Comment by Aikatsui** [comment]
> Fast fix for this is to use virtual webcam driver, like this one: http://classic.makesweet.com/webcam/ucanvcam/

Useless

**Comment by lipis** [comment]
In our latest release we improved the media device handling a lot. Please give it another try. :)

**Comment by KizunaH** [comment]
that's almost skype feature. - 2018-19 (not sure if they've changed with current development)

**Comment by KizunaH** [comment]
That's almost skype feature. - 2018-19 (not sure if they've changed with current development) 

**User Interface**
If application didn't detect both microphone and camera then only display voice call button in every contacts profile. (or possible to grayed out video call button). this must be applicable if application only detected microphone too.
If application only detected camera and no microphone then it's good to display only video call button (or grayed out voice call button) however skype only display voice call button for that (that skype method may mislead wire user)

**Important**
If caller side only has camera (no mic) and made a call then application should enable receiver side both camera and microphone automatically.
(However make sure to prevent conflict with no camera and microphone receivers)

when user make or answer any type of call then should display notification or warning immediately about what'll happen and how to fix it. (it must remain display unless manually close the notification)

It also good to display what wrong on each others devices separately. it may helpful for both participants decide whether keep call or not and help to fix.

**Receiver Side** 
Even no mic or cam on receiver device but able to answer as both voice or video depend on receive type

**Caller Side**
If no mic or cam on caller side then only able to make voice call (if video necessary then caller has to ask from receiver to enable video. If has camera and no mic then able to make video call however receiver side both camera and microphone should enable automatically as mentioned above

**Does that features affect to user privacy?**
Not really. Any person decide to make video call instead voice, chat to certain person because he/she may trust or know him/her otherwise usually for specific purposes eg: business. If someone think voice call still affect privacy somehow, it's better keep eye out from those buttons.

**Comment by thisisamir98** [comment]
Closing this as the user is already able to answer calls with no microphones or blocked microphone access.
