### ISSUE TITLE
Don't use Google for maps, use Open street map instead.

### ISSUE THREAD

**Issue by mat1th** [wireapp/wire-webapp#723]
Thank you for your nice app! 

I like your app because of the privacy aspect of the application. In your privacy statement you are saying: 'Wire does not sell your usage data to advertising companies.' But you are using the google service to place a marker on a map. It would be much more privacy friendly to use leaflet.js with open street map.

**Comment by noci2012** [comment]
i will agree to that.

**Comment by mohammadrafigh** [comment]
OSM tiles server is not a good way to go since it's just for testing purposes and not the production in large scale like Wire. so if Wire wants to switch to OSM then Wire needs a lot of storage and computing resources to maintain and provide maps on Wire servers, otherwise the only solution is relying on other 3rd party services like Google, MapBox, etc. and I consider all of them won't care too much about Wire users privacy. also another issue with OSM is that there is no open source native implementation of OSM for Android and iOS, so the Wire team needs to implement it using OpenGL (with keeping an eye on how MapBox did it) or just opening the map in a WebView with leaflet which may be a workaround.
so it seems there is no cheap and easy way for Wire to still keep the full privacy on maps.

**Comment by mat1th** [comment]
Thanks for your explanation. I understand that Wire is not using OSM. But I really do not like the way Google is collecting data. I think there are more private ones than the Google map for web. Maybe is [here maps](https://developer.here.com) an option

**Comment by noci2012** [comment]
Not sure why my item got a thumb down.. anyway.
You may also considder the next:   people using Wire might also use OsmAND , possibly with the maps already on the phone. (I do, and i am not alone)  OsmAnd uses the native OSM maps. (Or uses a tile server for maps). This way i don't need a live data connection during navigation.

In my case all (relevant) maps are already available, and they can be stored in a OsmAND private store or on a shared store. Either in Flash or on External SD.

http://osmand.net/

**Comment by forteller** [comment]
https://github.com/wireapp/wire-android/issues/734

**Comment by helenakos** [comment]
We don't have a committed date for changing this. Closing this issue only due to clean up purposes. We have noted it down internally.
