### ISSUE TITLE
Consider using different shortcuts for "Next/Previous Conversation"

### ISSUE THREAD

**Issue by max-baz** [wireapp/wire-webapp#733]
The combination <kbd>Alt+Shift+⬆/⬇</kbd> was a very poor choice to use as a shortcut, because <kbd>Alt+Shift</kbd> is often used to switch between language layouts. I found a workaround for myself to use <kbd>Shift+Alt+⬆/⬇</kbd>, but it's a dirty hack. Every time I forget to use it, I change my keyboard layout instead and get very annoyed 😤.

Can we get different shortcuts? Ideas:
- <kbd>Ctrl+Tab</kbd> and <kbd>Ctrl+Shift+Tab</kbd> (OK for desktop apps, conflicts with browsers' own shortcuts)
- <kbd>Ctrl+Shift+⬆/⬇</kbd> is my favorite, many other Wire shortcuts start with <kbd>Ctrl+Shift</kbd>.
- <kbd>Ctrl+Alt+⬆/⬇</kbd> might be another choice.

**Comment by bennycode** [comment]
Hey @maximbaz, I totally get your point. Also configurable shortcuts would be nice (so that everyone can use his/her favorite). 

Unfortunately our product owners don't plan to redesign keyboard shortcuts any time soon (https://github.com/wireapp/wire-webapp/issues/94#issuecomment-290714090). I will close this ticket here until we have other news.
