### ISSUE TITLE
Not able to login with "remember me" on FF51.0.1 (since FF50?)

### ISSUE THREAD

**Issue by 0ki** [wireapp/wire-webapp#734]
**I've not been able to use wire-webapp for at least a month now.** I though it might be stale cookies, so I finally braved myself to try a clean install today. No dice.
After entering my username and password, it just never loads. Attaching data:
http://02.lv/f/2017/02/07/wire.png
http://02.lv/f/2017/02/07/loader.png

(wire-app.min.js is 2017-02-03-10-46-prod)

**Comment by ffflorian** [comment]
@0ki Sorry, can't reproduce this on my machine. What do you mean by "clean install"? Did you reinstall the whole system or just the browser? If you just reinstalled Firefox, it's possible that it kept your whole data, including the cache - have you tried clearing the cache?

**Comment by 0ki** [comment]
I did incidentally reinstall my whole system, yes. 

I did some additional testing, and the problem manifests itself only when I check the "remember me" box.
When the box is not checked I immediately get the "your history won't appear here" message and I'm able to log in very fast.

Hope this helps.

**Comment by max-baz** [comment]
I have had a very similar experience once, usually I use desktop version and it always works fine, but when I tried web version, it stuck on loading, just like yours. I tried again and again over weeks, the issue didn't seem to be resolved, so I gave up on web version entirely.

Later I saw someone mentioning that this step of loading screen means that the app is decrypting your data. And if you have lots of data to decrypt, it will take lots of time. So out of curiosity I left my tab opened and went on doing other things, and guess what, after an hour or two the loading finished, and I was logged in!

It sounds a bit ridiculous, and I might be saying some imprecise information here, but our of curiosity, try leaving your tab opened on this loading stage for some time, maybe it will help?

**Comment by 0ki** [comment]
Thanks for the tip. Sounds reasonable. I'll try it tonight.

There is nothing to decrypt thought, since wire security model should not allow access to any of my previous info when logging in for the first time.

**Comment by gregor** [comment]
From the first screenshot I can tell that we found a previous database on your machine. At least 60.500 events vare in the queue to be decrypted. At least hitting the /notifications endpoint a multiple times indicates that. This will take a very long time.

**Comment by 0ki** [comment]
http://02.lv/f/2017/02/08/no-dice.png
I left the tab running for exactly **8 hours**.
The progress bar did move, but this is clearly a bug in at least two ways:
1) User has no clear feedback regarding the decryption process;
2) The process is clearly taking way too long.

**Comment by 0ki** [comment]
Somehow, old *wire* data had bled from my backup into my new installation.
Using "forget about this site" feature resolved the issue for me completely.

However:
Please don't close this issue, as there is still some improvements to be made at least to the UX.

**Comment by max-baz** [comment]
@gregor could you please share a bit more context, what 60.500 events is wire decrypting on startup? Or to start with, what exactly are the "events", different kinds of messages (text/image/link/ping/...)? Why not decrypt last 20 for every contact, and decrypt the rest on demand? Is it because the current algorithm simply cannot decrypt the last message without decrypting all the history first?

**Comment by herrmannplatz** [comment]
@maximbaz dont think the number of events is that high. Since half on the requests are actually CORS preflight requests.

So these are the events you would get over the websocket connection when you are online. This could be an encrypted message like Text, Image, Delivery Receipts, ... or just non encrypted event like conversation renaming etc. If you are offline these event are stored and we can requests them once the user is online. To answer your second questions. We need to ensure that we decrypted all messages for a client before you start sending a message to this this client.

@0ki we will not close this issue. we are working on improving the performance and also providing a better feedback of what we actually do.

**Comment by 0ki** [comment]
Do you still need more info?
