### ISSUE TITLE
Conversation list shows obsolete items

### ISSUE THREAD

**Issue by norstbox** [wireapp/wire-webapp#7405]
## Wire for web version
2019-09-24-11-57

## Browser version
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36

## Installed browser addons
None at all

## Operating system
Windows 10, 1903

## What steps will reproduce the problem?
Consider the following scenario:
1. Alice has a conversation with Bob
2. Bob has deleted his account
3. Alice invokes "Clear content..." action on the conversation with Bob
4. Alice logged in on a new device

## What is the expected result?
The conversation with Bob will not be shown on the list.

## What is the actual result?
The conversation list shows an empty item with ellipsis.

![conversation_list](https://user-images.githubusercontent.com/4142906/66420082-ee009200-ea0d-11e9-995c-d84b15bf0a62.png)

The issue seems to be wire-server related, although not reproduced on wire-android

**Comment by bennycode** [comment]
@norstbox do you know if these items belong to 1:1 conversations with users who got deleted?

**Comment by norstbox** [comment]
@bennyn yes, I am talking about 1:1 conversations. Do you have any issues with reproducing?

**Comment by bennycode** [comment]
Yes, we have issues reproducing this. It does not happen to us. Are you sure that the user/conversation you have been connected with is not deleted?

**Comment by norstbox** [comment]
>Are you sure that the user/conversation you have been connected with is not deleted?

Conversation can be deleted ("Clear content", to be more precise) on the specific device (see step 3 above), but it will reappear on the new device (step 4 above).

I just able to re-reproduce this behavior by the following steps:
1. Register new Wire Personal account
2. Connect it with my (already existing) account
3. Delete new account (from the step 1) by invoking ["Delete account" action](https://support.wire.com/hc/en-us/articles/207555795-Delete-a-Wire-Personal-account).
4. Remove user/conversation (corresponding to the deleted account) from my account by invoking "Clear content..." action
5. Log in to my account from new device ("PC-1")

Screenshot with obsolete/"orphaned" items from new device:
![wire-obsolete](https://user-images.githubusercontent.com/4142906/90014906-77c55f80-dcb0-11ea-9e4a-c51acdec3c77.png)

We can again remove these inappropriate items from device "PC-1" (by invoking "Clear content..."). Furthermore, if we log in on another new device "PC-2", obsolete items will reappear on "PC-2" **and "PC-1"** as well.

**Comment by bennycode** [comment]
Hi @norstbox, thanks for telling us steps to reproduce the issue. 

When you delete an account then we delete all meta information on our backend thus new devices (new PCs you use for login) won't get any info about the deleted user (i.e. name). That's why the conversation gets named "...". 

If you are using a [Wire for teams](https://wire.com/products/pro-secure-team-collaboration/) account (not personal) you will have the chance to completely delete this conversation. With personal accounts it is not possible to delete empty conversations on our backend, that's why you see this "annoying" conversation. I will pitch this problem to our product management.

Here is how you can completely delete a conversation from a "Wire for Teams" account:

![image](https://user-images.githubusercontent.com/469989/90405704-6d3a0a00-e0a4-11ea-8462-03337135597c.png)
