### ISSUE TITLE
Feature Request:  Display chat history when across all devices

### ISSUE THREAD

**Issue by SuperHaze** [wireapp/wire-webapp#770]
Hi guys, I use temporary work stations a lot (for work), so usually use web services like WhatsApp.  Only problem with using the web service for Wire, my chat histories aren't migrated when I open a new session in the webapp.  

I'm not sure how WhatsApp is able to migrate chats across device and web simultaneously while keeping E2E encryption, but was wondering if this could at least be an option.  Thanks

**Comment by SuperHaze** [comment]
Something I forgot to add!!!  Please, PLEASE give me an option to disable the e-mail "New device detected" every time I use a new webapp session.  Very annoying - I know this is also for security, so at least give me the option to disable.

**Comment by liocalset** [comment]
See #688

**Comment by bennycode** [comment]
The issue here can be solved by having a solution for https://github.com/wireapp/wire-webapp/issues/626

**Comment by helenakos** [comment]
Conversation history backup is on our list for the future. Therefore closing this issue.

**Comment by Sigmun** [comment]
Hi, I don't think this issue can be solved by #626 since the backup created is device type dependent, meaning I just create an iOS backup that I cannot restore on my webapp... What if I switch from iOS to Android ?
Please, this feature is a must... 

And I think that a manual sync of chat history from the Settings/Devices panel using this backup/restore feature can solve the problem described in #473. Honestly, I wish I can sync all my devices history one to each other so I never loose any conversation, even if one of my devices goes out of usage.

Please consider reopen this issue as a must have feature
