### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by mo3rfan** [wireapp/wire-webapp#83]
A dark theme option for the web app would be great. Just like we have for the Android app.

**Comment by helenakos** [comment]
Hey @PowerInside, thanks for the request! Noting it down for future :)

**Comment by fdelapuente** [comment]
Hi,

I see this was closed... meaning the Feature-Request was rejected and not considered for the future?

**Comment by helenakos** [comment]
@fdelapuente It is not rejected. We open tickets internally for feature requests and close them here.

**Comment by fdelapuente** [comment]
Hi @helenakos,

Thanks for the clarification. I can understand that the company doesn't want to expose its internal development process to the public, but ...

Wouldn't it be better to keep the public tickets open so that people can track the feature? 

You can always relate or link the internal tickets to the public ones... so that they'll be in sync.

From another perspective:  Imagine I wanted this feature (I do), I might have just filed a new feature request because I don't see any open tickets related to this topic... then you'll have to go and close it again... and again ... You see the advantage of keeping it open?  Anyone can then just track it instead of filing a new one...

Best Regards,
Felipe.

**Comment by helenakos** [comment]
@fdelapuente Reopening the issue here!

**Comment by jackmawer** [comment]
This would be much appreciated!

**Comment by liocalset** [comment]
Hi,

A dark theme would be a welcomed addition to the Web App. For me, it's easier on the eyes, especially at night. Thanks!

**Comment by helenakos** [comment]
Sadly I have to close the issue again. Trying to keep things tidy on github issues. 

We don't have a committed date or plans to do the dark theme. New, more functional design for desktop clients will come out in a matter of weeks. We are continuously working on making the clients better, however the resources are limited and dark theme hasn't been prioritised yet. 

On a side note, you can open an issue for general comments (not related to any client / specific repository) here: https://github.com/wireapp/wire

**Comment by ffflorian** [comment]
By the way, this was implemented in https://github.com/wireapp/wire-webapp/pull/5415 and will be published soon :tada:
