### ISSUE TITLE
Forced update link goes nowhere.

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-webapp#9294]
![image](https://user-images.githubusercontent.com/388716/88413802-d1212980-cda9-11ea-8e1a-a36abfedad54.png)

`https://medium.com/wire-news/desktop-updates`

Proper link would be `https://medium.com/wire-news/desktop-updates/home` and to be even more accurate it should be `https://medium.com/wire-news/link-medium-com-wire-news-wire-for-web/home` most of the time.

![image](https://user-images.githubusercontent.com/388716/88413826-df6f4580-cda9-11ea-9796-45da4f5c80af.png)

**Comment by ffflorian** [comment]
Hi @Transisto, the link https://medium.com/wire-news/desktop-updates is reachable for me, maybe Medium had a problem?

I will forward the link change proposal to our team.

**Comment by bennycode** [comment]
@Transisto, thank you very much for bringing this to our attention!

Apparently [Medium](http://medium.com/) changed the link structure from `/` to `/home`. We will fix this with our upcoming desktop release. Your suggestion to link to our webapp release notes is also a very good idea because the update banner is shown whenever the webapp inside our wrapper (desktop app) is updated.

I incorporated your suggestions in the following PR: https://github.com/wireapp/wire-desktop/pull/4085

**Comment by bennycode** [comment]
[Fixed with this PR](https://github.com/wireapp/wire-webapp/pull/9429). Will be included in our next public release.
