### ISSUE TITLE
firefox 50.1.0 showing "your browser doesn't support calls" error.

### ISSUE THREAD

**Issue by fdelapuente** [wireapp/wire-webapp#994]
Hi,

Recently in Ubuntu 17.04, firefox started giving errors to start and receive calls. It complains this version of firefox doesn't support calls. The version of firefox is 50.1.0 from Ubuntu Linux.

Thanks,
Felipe.

**Comment by gregor** [comment]
This is on purpose. The webRTC implementation in Firefox is evolving. We depend on some newer functionality with our rewritten calling implementation and in order to bring back the features currently disabled such as screensharing. The minimum required Firefox version for calling is now at 52, which will be their new ESR release moving forward.
